// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMpRp0IqkngLEl0esJdX0hX9yYYhDxV1E',
    appId: '1:730046956116:web:e58f909aafdd931af5e3c1',
    messagingSenderId: '730046956116',
    projectId: 'groceryapp-ee558',
    authDomain: 'groceryapp-ee558.firebaseapp.com',
    storageBucket: 'groceryapp-ee558.appspot.com',
    measurementId: 'G-0PPG2DBDP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcLD8O0sNYMRr_HWBCJUbGO_SMgJRlrFs',
    appId: '1:730046956116:android:9d81e989ea690e41f5e3c1',
    messagingSenderId: '730046956116',
    projectId: 'groceryapp-ee558',
    storageBucket: 'groceryapp-ee558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5WhVuB-11FAFIq5GynevHiO-z2UlCb8',
    appId: '1:730046956116:ios:8c650229e0a10e2ff5e3c1',
    messagingSenderId: '730046956116',
    projectId: 'groceryapp-ee558',
    storageBucket: 'groceryapp-ee558.appspot.com',
    iosClientId: '730046956116-ukk58h33or11q37unhrfnbs63na3v48u.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
